language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  # support codecov
  - pip install codecov
  - pip install pytest-cov
script:
  # use --cov=./ to generate coverage report
  - pytest --cov=./
# use codecov to upload coverage report
after_success:
  - codecov